### ISSUE TITLE
CF7 4 Support?

### ISSUE THREAD

**Issue by riyuk** [OddOneOut/Better-WordPress-reCAPTCHA#3]
Hi.

You've done a great job with that Plugin.
What does it need to upgrade it to Wordpress 4.1 & CF7 4.1? Do you have a Release-Date or Hotfix?

Currently the only output is [bwp-recaptcha ....]

**Comment by WillyXJ** [comment]
+1

**Comment by GoktugOzturk** [comment]
+1

**Comment by riyuk** [comment]
@WillyXJ @GoktugOzturk does anyone of you got a working solution?

**Comment by GoktugOzturk** [comment]
@riyuk Yes, uninstall and install https://wordpress.org/plugins/wp-recaptcha-integration/ :)
